### ISSUE TITLE
RuntimeError: size unmatched

### ISSUE THREAD

**Issue by zimingzhong** [TEXTurePaper/TEXTurePaper#13]
Traceback (most recent call last):
  File "/public/home/zhongzm/anaconda3/envs/latent/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/public/home/zhongzm/anaconda3/envs/latent/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/public/home/zhongzm/project/TEXTurePaper/scripts/run_texture.py", line 17, in <module>
    main()
  File "/public/home/zhongzm/anaconda3/envs/latent/lib/python3.8/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/public/home/zhongzm/project/TEXTurePaper/scripts/run_texture.py", line 13, in main
    trainer.paint()
  File "/public/home/zhongzm/project/TEXTurePaper/src/training/trainer.py", line 131, in paint
    self.paint_viewpoint(data)
  File "/public/home/zhongzm/project/TEXTurePaper/src/training/trainer.py", line 271, in paint_viewpoint
    cropped_rgb_output, steps_vis = self.diffusion.img2img_step(text_z, cropped_rgb_render.detach(),
  File "/public/home/zhongzm/project/TEXTurePaper/src/stable_diffusion_depth.py", line 295, in img2img_step
    target_latents = sample(latents, depth_mask, strength=strength, num_inference_steps=num_inference_steps,
  File "/public/home/zhongzm/project/TEXTurePaper/src/stable_diffusion_depth.py", line 223, in sample
    latents = latents * curr_mask + noised_truth * (1 - curr_mask)
RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1
 10% painting step 1/10 [00:08<01:14,  8.32s/it]

the latents dims is 3 and the noised_truth dims is 4

**Comment by FrankYoungchen** [comment]
how to solve the problem? please

**Comment by 2454511550Lin** [comment]
I encounter the same issue. For me, I accidentally passed in a PNG file with 4 channels, it should be 3. You can check the bit size of your image file, it should be 24 not 32. An easier fix is to just use JPG format, so that all the image have 3 channels? (At least it worked for me)
