### ISSUE TITLE
ValueError: tile cannot extend outside image

### ISSUE THREAD

**Issue by pixelknit** [TEXTurePaper/TEXTurePaper#28]
Hello, I'm having this issue, it used to happen regularly, it seemed kind of random, sometime it happened, but after the 4 try or something it went through, but now I can't generate a single texture, I haven't changed the code, I'm generating 3d geometry, then using this repo to do the texturing, but I get this message all the time: **ValueError: tile cannot extend outside image**
This is coming from PIL/Image.py when it tries to save the image, so: src/training/trainer.py will fail.
I'm printing the shape of the tensor on trainer.py on the log_train_image method, I can see the shapes as it goes through the paining steps: it always fails at step # 9, for some reason the shape at this step is always (0, 1149, 3), that 0 dimension is making everythin down the chain fail:

 90% painting step 9/10 [02:23<00:18, 18.91s/it]The Tensor shape is:  (1200, 1200, 3)
The Tensor shape is:  (1200, 1200, 3)
The Tensor shape is:  (1200, 1200, 3)
The Tensor shape is:  (1200, 1200, 3)
ic| crop: <function TEXTure.paint_viewpoint.<locals>.<lambda> at 0x000001C04A362830>
The Tensor shape is:  (0, 1149, 3)
Traceback (most recent call last):
  File "C:\Users\FelipePesantez\anaconda3\envs\torch\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\FelipePesantez\anaconda3\envs\torch\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\FelipePesantez\development\generative_ai\TEXTurePaper\scripts\run_texture.py", line 17, in <module>
    main()
  File "C:\Users\FelipePesantez\anaconda3\envs\torch\lib\site-packages\pyrallis\argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "C:\Users\FelipePesantez\development\generative_ai\TEXTurePaper\scripts\run_texture.py", line 13, in main
    trainer.paint()
  File "C:\Users\FelipePesantez\development\generative_ai\TEXTurePaper\src\training\trainer.py", line 132, in paint
    self.paint_viewpoint(data)
  File "C:\Users\FelipePesantez\development\generative_ai\TEXTurePaper\src\training\trainer.py", line 263, in paint_viewpoint
    self.log_train_image(cropped_rgb_render, name='cropped_input')
  File "C:\Users\FelipePesantez\development\generative_ai\TEXTurePaper\src\training\trainer.py", line 490, in log_train_image
    Image.fromarray((tensor * 255).astype(np.uint8)).save(
  File "C:\Users\FelipePesantez\anaconda3\envs\torch\lib\site-packages\PIL\Image.py", line 3013, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "C:\Users\FelipePesantez\anaconda3\envs\torch\lib\site-packages\PIL\Image.py", line 2940, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "C:\Users\FelipePesantez\anaconda3\envs\torch\lib\site-packages\PIL\Image.py", line 2882, in frombytes
    im.frombytes(data, decoder_name, args)
  File "C:\Users\FelipePesantez\anaconda3\envs\torch\lib\site-packages\PIL\Image.py", line 811, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image
 90% painting step 9/10 [02:23<00:15, 15.92s/it]

**Comment by qk98** [comment]
![image](https://github.com/TEXTurePaper/TEXTurePaper/assets/3952934/3526ebd3-89c6-419c-a809-7c92348d4434)

**Comment by pixelknit** [comment]
@qk98 Amazing! that worked indeed, thank you so much :)
