### ISSUE TITLE
colab training error !

### ISSUE THREAD

**Issue by kotaxyz** [TEXTurePaper/TEXTurePaper#40]
all other scripts works fine but i get an error when runing training

python -m scripts.finetune_diffusion --pretrained_model_name_or_path=stabilityai/stable-diffusion-2-depth --instance_data_dir=images/teapot_processed --instance_prompt="a photo of a teapot" --lr_warmup_steps=0 --max_train_steps=10000 --scale_lr --output_dir tuned_models/teapot_model --eval_path=configs/texture_transfer/eval_data.json

/content/TEXTurePaper/scripts/finetune_diffusion.py:16: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import ImagePipelineOutput
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/TEXTurePaper/scripts/finetune_diffusion.py", line 930, in <module>
    main(args)
  File "/content/TEXTurePaper/scripts/finetune_diffusion.py", line 493, in main
    accelerator = Accelerator(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 382, in __init__
    trackers = filter_trackers(log_with, self.logging_dir)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/tracking.py", line 736, in filter_trackers
    raise ValueError(
ValueError: Logging with `tensorboard` requires a `logging_dir` to be passed in.

**Comment by eladrich** [comment]
You can see that the raised error is specifically from the accelerator initialization, try to specify a logging sir or remove the log_with option
