### ISSUE TITLE
out of memory while training !

### ISSUE THREAD

**Issue by kotaxyz** [TEXTurePaper/TEXTurePaper#41]
i get out of memory on 15 gb vram card how i fix this, usage spikes here 10/1000 and it give error rather than that it utilizes arround 13.7 gb
i tried mixed_precision but it gives error 

ValueError: Attempting to unscale FP16 gradients

here is the log

!python -m scripts.finetune_diffusion --pretrained_model_name_or_path=stabilityai/stable-diffusion-2-depth --instance_data_dir=images/teapot_processed --instance_prompt="a photo of a teapot" --lr_warmup_steps=0 --max_train_steps=1000 --scale_lr --output_dir tuned_models/teapot_model --eval_path=configs/texture_transfer/eval_data.json --train_batch_size 1 --gradient_checkpointing --gradient_accumulation_steps=1 --sample_batch_size 1  --use_8bit_adam  --resolution 512 --num_train_epochs 1 --max_grad_norm 1.0

2023-11-06 16:30:19.435948: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-06 16:30:19.436005: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-06 16:30:19.436035: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-06 16:30:20.826287: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Using object as an initial word
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
==============================WARNING: DEPRECATED!==============================
WARNING! This version of bitsandbytes is deprecated. Please switch to `pip install bitsandbytes` and the new repo: https://github.com/TimDettmers/bitsandbytes
==============================WARNING: DEPRECATED!==============================
/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py:215: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a scheduler, please use <class 'diffusers.schedulers.scheduling_ddpm.DDPMScheduler'>.from_pretrained(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)
[PosixPath('images/teapot_processed/2.jpeg'), PosixPath('images/teapot_processed/4.jpeg'), PosixPath('images/teapot_processed/3.jpeg'), PosixPath('images/teapot_processed/1.jpeg'), PosixPath('images/teapot_processed/5.jpeg')]
Steps:   0% 0/1000 [00:00<?, ?it/s]a photo of a teapot [49406, 320, 1125, 539, 320, 40749, 49407]
a photo of a teapot [49406, 320, 1125, 539, 320, 40749, 49407]
Steps:   0% 1/1000 [00:02<44:53,  2.70s/it, loss=0.00312, lr=5e-6]a photo of a teapot [49406, 320, 1125, 539, 320, 40749, 49407]
Steps:   0% 2/1000 [00:04<31:58,  1.92s/it, loss=0.188, lr=5e-6]  a photo of a teapot [49406, 320, 1125, 539, 320, 40749, 49407]
Steps:   0% 3/1000 [00:05<28:17,  1.70s/it, loss=0.6, lr=5e-6]  a photo of a teapot [49406, 320, 1125, 539, 320, 40749, 49407]
Steps:   0% 5/1000 [00:08<25:27,  1.53s/it, loss=0.572, lr=5e-6] a photo of a teapot [49406, 320, 1125, 539, 320, 40749, 49407]
a photo of a teapot [49406, 320, 1125, 539, 320, 40749, 49407]
Steps:   1% 6/1000 [00:09<24:52,  1.50s/it, loss=0.0307, lr=5e-6]a photo of a teapot [49406, 320, 1125, 539, 320, 40749, 49407]
Steps:   1% 7/1000 [00:11<24:30,  1.48s/it, loss=0.0529, lr=5e-6]a photo of a teapot [49406, 320, 1125, 539, 320, 40749, 49407]
Steps:   1% 8/1000 [00:12<24:16,  1.47s/it, loss=0.00672, lr=5e-6]a photo of a teapot [49406, 320, 1125, 539, 320, 40749, 49407]
Steps:   1% 10/1000 [00:15<23:58,  1.45s/it, loss=0.321, lr=5e-6]/content/TEXTurePaper/scripts/finetune_diffusion.py:308: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet2DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet2DConditionModel's config object instead, e.g. 'unet.config.in_channels'.
  latents = torch.randn((text_embeddings.shape[0] // 2, self.unet.in_channels - 1, 64, 64),

  0% 0/50 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
  0% 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/TEXTurePaper/scripts/finetune_diffusion.py", line 930, in <module>
    main(args)
  File "/content/TEXTurePaper/scripts/finetune_diffusion.py", line 894, in main
    eval_pipeline(pipeline, args.eval_path, args.instance_prompt, global_step, vis_save_dir,
  File "/content/TEXTurePaper/scripts/finetune_diffusion.py", line 365, in eval_pipeline
    img = call_pipeline_without_image(pipeline, prompt, depth).images[0]
  File "/content/TEXTurePaper/scripts/finetune_diffusion.py", line 324, in call_pipeline_without_image
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 724, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_blocks.py", line 859, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_blocks.py", line 852, in custom_forward
    return module(*inputs, return_dict=return_dict)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention.py", line 313, in forward
    attn_output = self.attn1(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 267, in forward
    return self.processor(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 406, in __call__
    attention_probs = attn.get_attention_scores(query, key, attention_mask)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 319, in get_attention_scores
    attention_probs = attention_scores.softmax(dim=-1)
RuntimeError: CUDA out of memory. Tried to allocate 640.00 MiB (GPU 0; 14.75 GiB total capacity; 12.29 GiB already allocated; 370.81 MiB free; 13.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   1% 10/1000 [00:17<29:11,  1.77s/it, loss=0.321, lr=5e-6]

**Comment by eladrich** [comment]
We don't have a solution for that, maybe try to take a look at related issues in the diffusers repo
